version: 2

sources:
  - name: erpNorthwind16102021
    description: This is a replica of the Postgres database used by our app.
    tables:
      - name: public_orders
        description: chaveid
        columns:
          - name: order_id
            description: Primary key of the orders table
          - name: products
            description: Esta tabela contem informação sobre os produtos da Northwind.
          - name: shippers
            description: Esta tabela contem informação sobre os entregadores da Northwind.
          - name: employees
            description: Esta tabela contem informação sobre os colaboradores da Northwind.
          - name: customers
            description: Esta tabela contem informação sobre os clientes da Northwind.
          - name: suppliers
            description: Esta tabela contem informação sobre os fornecedores da Northwind.