version: 2

sources:
  - name: erpNorthwind16102021
    description: This is a replica of the Postgres database used by our client
    tables:
      - name: public_orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
          - name: public_orders id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null